const VOCABULARY = [
  [
    1,
    'I',
    'amāre',
    'love / любить',
    ['am_ō', 'amā_s', 'ama_t'],
    ['amā_mus', 'amā_tis', 'ama_nt'],
  ],
  [
    2,
    'I',
    'amāre',
    'love / любить',
    ['am_or', 'amā_ris', 'amā_tur'],
    ['amā_mur', 'amā_minī', 'ama_ntur'],
  ],
  [
    3,
    'I',
    'amāre',
    'love / любить',
    ['amāba_m', 'amābā_s', 'amāba_t'],
    ['amābā_mus', 'amābā_tis', 'amāba_nt'],
  ],
  [
    4,
    'I',
    'amāre',
    'love / любить',
    ['amāba_r', 'amābā_ris', 'amābā_tur'],
    ['amābā_mur', 'amābā_minī', 'amāba_ntur'],
  ],
  [
    5,
    'I',
    'amāre',
    'love / любить',
    ['amāb_ō', 'amābi_s', 'amābi_t'],
    ['amābi_mus', 'amābi_tis', 'amābu_nt'],
  ],
  [
    6,
    'I',
    'amāre',
    'love / любить',
    ['amāb_or', 'amābe_ris', 'amābi_tur'],
    ['amābi_mur', 'amābi_minī', 'amābu_ntur'],
  ],
  [
    13,
    'I',
    'amāre',
    'love / любить',
    ['', 'amā', ''],
    ['', 'amā_te', ''],
  ],
  [
    14,
    'I',
    'amāre',
    'love / любить',
    ['', 'amā_re', ''],
    ['', 'amā_minī', ''],
  ],
  [
    1,
    'I',
    'clāmāre',
    'cry, shout / кричать',
    ['clām_ō', 'clāmā_s', 'clāma_t'],
    ['clāmā_mus', 'clāmā_tis', 'clāma_nt'],
  ],
  [
    2,
    'I',
    'clāmāre',
    'cry, shout / кричать',
    ['clām_or', 'clāmā_ris', 'clāmā_tur'],
    ['clāmā_mur', 'clāmā_minī', 'clāma_ntur'],
  ],
  [
    3,
    'I',
    'clāmāre',
    'cry, shout / кричать',
    ['clāmāba_m', 'clāmābā_s', 'clāmāba_t'],
    ['clāmābā_mus', 'clāmābā_tis', 'clāmāba_nt'],
  ],
  [
    4,
    'I',
    'clāmāre',
    'cry, shout / кричать',
    ['clāmāba_r', 'clāmābā_ris', 'clāmābā_tur'],
    ['clāmābā_mur', 'clāmābā_minī', 'clāmāba_ntur'],
  ],
  [
    5,
    'I',
    'clāmāre',
    'cry, shout / кричать',
    ['clāmāb_ō', 'clāmābi_s', 'clāmābi_t'],
    ['clāmābi_mus', 'clāmābi_tis', 'clāmābu_nt'],
  ],
  [
    6,
    'I',
    'clāmāre',
    'cry, shout / кричать',
    ['clāmāb_or', 'clāmābe_ris', 'clāmābi_tur'],
    ['clāmābi_mur', 'clāmābi_minī', 'clāmābu_ntur'],
  ],
  [
    13,
    'I',
    'clāmāre',
    'cry, shout / кричать',
    ['', 'clāmā', ''],
    ['', 'clāmā_te', ''],
  ],
  [
    14,
    'I',
    'clāmāre',
    'cry, shout / кричать',
    ['', 'clāmā_re', ''],
    ['', 'clāmā_minī', ''],
  ],
  [
    1,
    'I',
    'rogāre',
    'ask / спрашивать',
    ['rog_ō', 'rogā_s', 'roga_t'],
    ['rogā_mus', 'rogā_tis', 'roga_nt'],
  ],
  [
    2,
    'I',
    'rogāre',
    'ask / спрашивать',
    ['rog_or', 'rogā_ris', 'rogā_tur'],
    ['rogā_mur', 'rogā_minī', 'roga_ntur'],
  ],
  [
    3,
    'I',
    'rogāre',
    'ask / спрашивать',
    ['rogāba_m', 'rogābā_s', 'rogāba_t'],
    ['rogābā_mus', 'rogābā_tis', 'rogāba_nt'],
  ],
  [
    4,
    'I',
    'rogāre',
    'ask / спрашивать',
    ['rogāba_r', 'rogābā_ris', 'rogābā_tur'],
    ['rogābā_mur', 'rogābā_minī', 'rogāba_ntur'],
  ],
  [
    5,
    'I',
    'rogāre',
    'ask / спрашивать',
    ['rogāb_ō', 'rogābi_s', 'rogābi_t'],
    ['rogābi_mus', 'rogābi_tis', 'rogābu_nt'],
  ],
  [
    6,
    'I',
    'rogāre',
    'ask / спрашивать',
    ['rogāb_or', 'rogābe_ris', 'rogābi_tur'],
    ['rogābi_mur', 'rogābi_minī', 'rogābu_ntur'],
  ],
  [
    13,
    'I',
    'rogāre',
    'ask / спрашивать',
    ['', 'rogā', ''],
    ['', 'rogā_te', ''],
  ],
  [
    14,
    'I',
    'rogāre',
    'ask / спрашивать',
    ['', 'rogā_re', ''],
    ['', 'rogā_minī', ''],
  ],
  [
    1,
    'I',
    'levāre',
    'elevate / поднимать, повышать',
    ['lev_ō', 'levā_s', 'leva_t'],
    ['levā_mus', 'levā_tis', 'leva_nt'],
  ],
  [
    2,
    'I',
    'levāre',
    'elevate / поднимать, повышать',
    ['lev_or', 'levā_ris', 'levā_tur'],
    ['levā_mur', 'levā_minī', 'leva_ntur'],
  ],
  [
    3,
    'I',
    'levāre',
    'elevate / поднимать, повышать',
    ['levāba_m', 'levābā_s', 'levāba_t'],
    ['levābā_mus', 'levābā_tis', 'levāba_nt'],
  ],
  [
    4,
    'I',
    'levāre',
    'elevate / поднимать, повышать',
    ['levāba_r', 'levābā_ris', 'levābā_tur'],
    ['levābā_mur', 'levābā_minī', 'levāba_ntur'],
  ],
  [
    5,
    'I',
    'levāre',
    'elevate / поднимать, повышать',
    ['levāb_ō', 'levābi_s', 'levābi_t'],
    ['levābi_mus', 'levābi_tis', 'levābu_nt'],
  ],
  [
    6,
    'I',
    'levāre',
    'elevate / поднимать, повышать',
    ['levāb_or', 'levābe_ris', 'levābi_tur'],
    ['levābi_mur', 'levābi_minī', 'levābu_ntur'],
  ],
  [
    13,
    'I',
    'levāre',
    'elevate / поднимать, повышать',
    ['', 'levā', ''],
    ['', 'levā_te', ''],
  ],
  [
    14,
    'I',
    'levāre',
    'elevate / поднимать, повышать',
    ['', 'levā_re', ''],
    ['', 'levā_minī', ''],
  ],
  [
    1,
    'I',
    'iterāre',
    'repeat / повторять',
    ['iter_ō', 'iterā_s', 'itera_t'],
    ['iterā_mus', 'iterā_tis', 'itera_nt'],
  ],
  [
    2,
    'I',
    'iterāre',
    'repeat / повторять',
    ['iter_or', 'iterā_ris', 'iterā_tur'],
    ['iterā_mur', 'iterā_minī', 'itera_ntur'],
  ],
  [
    3,
    'I',
    'iterāre',
    'repeat / повторять',
    ['iterāba_m', 'iterābā_s', 'iterāba_t'],
    ['iterābā_mus', 'iterābā_tis', 'iterāba_nt'],
  ],
  [
    4,
    'I',
    'iterāre',
    'repeat / повторять',
    ['iterāba_r', 'iterābā_ris', 'iterābā_tur'],
    ['iterābā_mur', 'iterābā_minī', 'iterāba_ntur'],
  ],
  [
    5,
    'I',
    'iterāre',
    'repeat / повторять',
    ['iterāb_ō', 'iterābi_s', 'iterābi_t'],
    ['iterābi_mus', 'iterābi_tis', 'iterābu_nt'],
  ],
  [
    6,
    'I',
    'iterāre',
    'repeat / повторять',
    ['iterāb_or', 'iterābe_ris', 'iterābi_tur'],
    ['iterābi_mur', 'iterābi_minī', 'iterābu_ntur'],
  ],
  [
    13,
    'I',
    'iterāre',
    'repeat / повторять',
    ['', 'iterā', ''],
    ['', 'iterā_te', ''],
  ],
  [
    14,
    'I',
    'iterāre',
    'repeat / повторять',
    ['', 'iterā_re', ''],
    ['', 'iterā_minī', ''],
  ],
  [
    1,
    'I',
    'aedificāre',
    'build / строить',
    ['aedific_ō', 'aedificā_s', 'aedifica_t'],
    ['aedificā_mus', 'aedificā_tis', 'aedifica_nt'],
  ],
  [
    2,
    'I',
    'aedificāre',
    'build / строить',
    ['aedific_or', 'aedificā_ris', 'aedificā_tur'],
    ['aedificā_mur', 'aedificā_minī', 'aedifica_ntur'],
  ],
  [
    3,
    'I',
    'aedificāre',
    'build / строить',
    ['aedificāba_m', 'aedificābā_s', 'aedificāba_t'],
    ['aedificābā_mus', 'aedificābā_tis', 'aedificāba_nt'],
  ],
  [
    4,
    'I',
    'aedificāre',
    'build / строить',
    ['aedificāba_r', 'aedificābā_ris', 'aedificābā_tur'],
    ['aedificābā_mur', 'aedificābā_minī', 'aedificāba_ntur'],
  ],
  [
    5,
    'I',
    'aedificāre',
    'build / строить',
    ['aedificāb_ō', 'aedificābi_s', 'aedificābi_t'],
    ['aedificābi_mus', 'aedificābi_tis', 'aedificābu_nt'],
  ],
  [
    6,
    'I',
    'aedificāre',
    'build / строить',
    ['aedificāb_or', 'aedificābe_ris', 'aedificābi_tur'],
    ['aedificābi_mur', 'aedificābi_minī', 'aedificābu_ntur'],
  ],
  [
    13,
    'I',
    'aedificāre',
    'build / строить',
    ['', 'aedificā', ''],
    ['', 'aedificā_te', ''],
  ],
  [
    14,
    'I',
    'aedificāre',
    'build / строить',
    ['', 'aedificā_re', ''],
    ['', 'aedificā_minī', ''],
  ],
  [
    1,
    'I',
    'vocāre',
    'call / звать',
    ['voc_ō', 'vocā_s', 'voca_t'],
    ['vocā_mus', 'vocā_tis', 'voca_nt'],
  ],
  [
    2,
    'I',
    'vocāre',
    'call / звать',
    ['voc_or', 'vocā_ris', 'vocā_tur'],
    ['vocā_mur', 'vocā_minī', 'voca_ntur'],
  ],
  [
    3,
    'I',
    'vocāre',
    'call / звать',
    ['vocāba_m', 'vocābā_s', 'vocāba_t'],
    ['vocābā_mus', 'vocābā_tis', 'vocāba_nt'],
  ],
  [
    4,
    'I',
    'vocāre',
    'call / звать',
    ['vocāba_r', 'vocābā_ris', 'vocābā_tur'],
    ['vocābā_mur', 'vocābā_minī', 'vocāba_ntur'],
  ],
  [
    5,
    'I',
    'vocāre',
    'call / звать',
    ['vocāb_ō', 'vocābi_s', 'vocābi_t'],
    ['vocābi_mus', 'vocābi_tis', 'vocābu_nt'],
  ],
  [
    6,
    'I',
    'vocāre',
    'call / звать',
    ['vocāb_or', 'vocābe_ris', 'vocābi_tur'],
    ['vocābi_mur', 'vocābi_minī', 'vocābu_ntur'],
  ],
  [
    13,
    'I',
    'vocāre',
    'call / звать',
    ['', 'vocā', ''],
    ['', 'vocā_te', ''],
  ],
  [
    14,
    'I',
    'vocāre',
    'call / звать',
    ['', 'vocā_re', ''],
    ['', 'vocā_minī', ''],
  ],
  [
    1,
    'I',
    'cantāre',
    'sing / петь',
    ['cant_ō', 'cantā_s', 'canta_t'],
    ['cantā_mus', 'cantā_tis', 'canta_nt'],
  ],
  [
    2,
    'I',
    'cantāre',
    'sing / петь',
    ['cant_or', 'cantā_ris', 'cantā_tur'],
    ['cantā_mur', 'cantā_minī', 'canta_ntur'],
  ],
  [
    3,
    'I',
    'cantāre',
    'sing / петь',
    ['cantāba_m', 'cantābā_s', 'cantāba_t'],
    ['cantābā_mus', 'cantābā_tis', 'cantāba_nt'],
  ],
  [
    4,
    'I',
    'cantāre',
    'sing / петь',
    ['cantāba_r', 'cantābā_ris', 'cantābā_tur'],
    ['cantābā_mur', 'cantābā_minī', 'cantāba_ntur'],
  ],
  [
    5,
    'I',
    'cantāre',
    'sing / петь',
    ['cantāb_ō', 'cantābi_s', 'cantābi_t'],
    ['cantābi_mus', 'cantābi_tis', 'cantābu_nt'],
  ],
  [
    6,
    'I',
    'cantāre',
    'sing / петь',
    ['cantāb_or', 'cantābe_ris', 'cantābi_tur'],
    ['cantābi_mur', 'cantābi_minī', 'cantābu_ntur'],
  ],
  [
    13,
    'I',
    'cantāre',
    'sing / петь',
    ['', 'cantā', ''],
    ['', 'cantā_te', ''],
  ],
  [
    14,
    'I',
    'cantāre',
    'sing / петь',
    ['', 'cantā_re', ''],
    ['', 'cantā_minī', ''],
  ],
  [
    1,
    'I',
    'numerāre',
    'count / считать',
    ['numer_ō', 'numerā_s', 'numera_t'],
    ['numerā_mus', 'numerā_tis', 'numera_nt'],
  ],
  [
    2,
    'I',
    'numerāre',
    'count / считать',
    ['numer_or', 'numerā_ris', 'numerā_tur'],
    ['numerā_mur', 'numerā_minī', 'numera_ntur'],
  ],
  [
    3,
    'I',
    'numerāre',
    'count / считать',
    ['numerāba_m', 'numerābā_s', 'numerāba_t'],
    ['numerābā_mus', 'numerābā_tis', 'numerāba_nt'],
  ],
  [
    4,
    'I',
    'numerāre',
    'count / считать',
    ['numerāba_r', 'numerābā_ris', 'numerābā_tur'],
    ['numerābā_mur', 'numerābā_minī', 'numerāba_ntur'],
  ],
  [
    5,
    'I',
    'numerāre',
    'count / считать',
    ['numerāb_ō', 'numerābi_s', 'numerābi_t'],
    ['numerābi_mus', 'numerābi_tis', 'numerābu_nt'],
  ],
  [
    6,
    'I',
    'numerāre',
    'count / считать',
    ['numerāb_or', 'numerābe_ris', 'numerābi_tur'],
    ['numerābi_mur', 'numerābi_minī', 'numerābu_ntur'],
  ],
  [
    13,
    'I',
    'numerāre',
    'count / считать',
    ['', 'numerā', ''],
    ['', 'numerā_te', ''],
  ],
  [
    14,
    'I',
    'numerāre',
    'count / считать',
    ['', 'numerā_re', ''],
    ['', 'numerā_minī', ''],
  ],
  [
    1,
    'I',
    'salūtāre',
    'greet / приветствовать',
    ['salūt_ō', 'salūtā_s', 'salūta_t'],
    ['salūtā_mus', 'salūtā_tis', 'salūta_nt'],
  ],
  [
    2,
    'I',
    'salūtāre',
    'greet / приветствовать',
    ['salūt_or', 'salūtā_ris', 'salūtā_tur'],
    ['salūtā_mur', 'salūtā_minī', 'salūta_ntur'],
  ],
  [
    3,
    'I',
    'salūtāre',
    'greet / приветствовать',
    ['salūtāba_m', 'salūtābā_s', 'salūtāba_t'],
    ['salūtābā_mus', 'salūtābā_tis', 'salūtāba_nt'],
  ],
  [
    4,
    'I',
    'salūtāre',
    'greet / приветствовать',
    ['salūtāba_r', 'salūtābā_ris', 'salūtābā_tur'],
    ['salūtābā_mur', 'salūtābā_minī', 'salūtāba_ntur'],
  ],
  [
    5,
    'I',
    'salūtāre',
    'greet / приветствовать',
    ['salūtāb_ō', 'salūtābi_s', 'salūtābi_t'],
    ['salūtābi_mus', 'salūtābi_tis', 'salūtābu_nt'],
  ],
  [
    6,
    'I',
    'salūtāre',
    'greet / приветствовать',
    ['salūtāb_or', 'salūtābe_ris', 'salūtābi_tur'],
    ['salūtābi_mur', 'salūtābi_minī', 'salūtābu_ntur'],
  ],
  [
    13,
    'I',
    'salūtāre',
    'greet / приветствовать',
    ['', 'salūtā', ''],
    ['', 'salūtā_te', ''],
  ],
  [
    14,
    'I',
    'salūtāre',
    'greet / приветствовать',
    ['', 'salūtā_re', ''],
    ['', 'salūtā_minī', ''],
  ],
  [
    1,
    'II',
    'videō vīdī vīsum -ēre',
    'see / видеть',
    ['vide_ō', 'vidē_s', 'vide_t'],
    ['vidē_mus', 'vidē_tis', 'vide_nt'],
  ],
  [
    2,
    'II',
    'videō vīdī vīsum -ēre',
    'see / видеть',
    ['vide_or', 'vidē_ris', 'vidē_tur'],
    ['vidē_mur', 'vidē_minī', 'vide_ntur'],
  ],
  [
    3,
    'II',
    'videō vīdī vīsum -ēre',
    'see / видеть',
    ['vidēba_m', 'vidēbā_s', 'vidēba_t'],
    ['vidēbā_mus', 'vidēbā_tis', 'vidēba_nt'],
  ],
  [
    4,
    'II',
    'videō vīdī vīsum -ēre',
    'see / видеть',
    ['vidēba_r', 'vidēbā_ris', 'vidēbā_tur'],
    ['vidēbā_mur', 'vidēbā_minī', 'vidēba_ntur'],
  ],
  [
    5,
    'II',
    'videō vīdī vīsum -ēre',
    'see / видеть',
    ['vidēb_ō', 'vidēbi_s', 'vidēbi_t'],
    ['vidēbi_mus', 'vidēbi_tis', 'vidēbu_nt'],
  ],
  [
    6,
    'II',
    'videō vīdī vīsum -ēre',
    'see / видеть',
    ['vidēb_or', 'vidēbe_ris', 'vidēbi_tur'],
    ['vidēbi_mur', 'vidēbi_minī', 'vidēbu_ntur'],
  ],
  [
    13,
    'II',
    'videō vīdī vīsum -ēre',
    'see / видеть',
    ['', 'vidē', ''],
    ['', 'vidē_te', ''],
  ],
  [
    14,
    'II',
    'videō vīdī vīsum -ēre',
    'see / видеть',
    ['', 'vidē_re', ''],
    ['', 'vidē_minī', ''],
  ],
  [
    1,
    'II',
    'respondeō -dī -sum -ēre',
    'answer / отвечать',
    ['responde_ō', 'respondē_s', 'responde_t'],
    ['respondē_mus', 'respondē_tis', 'responde_nt'],
  ],
  [
    2,
    'II',
    'respondeō -dī -sum -ēre',
    'answer / отвечать',
    ['responde_or', 'respondē_ris', 'respondē_tur'],
    ['respondē_mur', 'respondē_minī', 'responde_ntur'],
  ],
  [
    3,
    'II',
    'respondeō -dī -sum -ēre',
    'answer / отвечать',
    ['respondēba_m', 'respondēbā_s', 'respondēba_t'],
    ['respondēbā_mus', 'respondēbā_tis', 'respondēba_nt'],
  ],
  [
    4,
    'II',
    'respondeō -dī -sum -ēre',
    'answer / отвечать',
    ['respondēba_r', 'respondēbā_ris', 'respondēbā_tur'],
    ['respondēbā_mur', 'respondēbā_minī', 'respondēba_ntur'],
  ],
  [
    5,
    'II',
    'respondeō -dī -sum -ēre',
    'answer / отвечать',
    ['respondēb_ō', 'respondēbi_s', 'respondēbi_t'],
    ['respondēbi_mus', 'respondēbi_tis', 'respondēbu_nt'],
  ],
  [
    6,
    'II',
    'respondeō -dī -sum -ēre',
    'answer / отвечать',
    ['respondēb_or', 'respondēbe_ris', 'respondēbi_tur'],
    ['respondēbi_mur', 'respondēbi_minī', 'respondēbu_ntur'],
  ],
  [
    13,
    'II',
    'respondeō -dī -sum -ēre',
    'answer / отвечать',
    ['', 'respondē', ''],
    ['', 'respondē_te', ''],
  ],
  [
    14,
    'II',
    'respondeō -dī -sum -ēre',
    'answer / отвечать',
    ['', 'respondē_re', ''],
    ['', 'respondē_minī', ''],
  ],
  [
    1,
    'II',
    'habēre',
    'have / иметь',
    ['habe_ō', 'habē_s', 'habe_t'],
    ['habē_mus', 'habē_tis', 'habe_nt'],
  ],
  [
    2,
    'II',
    'habēre',
    'have / иметь',
    ['habe_or', 'habē_ris', 'habē_tur'],
    ['habē_mur', 'habē_minī', 'habe_ntur'],
  ],
  [
    3,
    'II',
    'habēre',
    'have / иметь',
    ['habēba_m', 'habēbā_s', 'habēba_t'],
    ['habēbā_mus', 'habēbā_tis', 'habēba_nt'],
  ],
  [
    4,
    'II',
    'habēre',
    'have / иметь',
    ['habēba_r', 'habēbā_ris', 'habēbā_tur'],
    ['habēbā_mur', 'habēbā_minī', 'habēba_ntur'],
  ],
  [
    5,
    'II',
    'habēre',
    'have / иметь',
    ['habēb_ō', 'habēbi_s', 'habēbi_t'],
    ['habēbi_mus', 'habēbi_tis', 'habēbu_nt'],
  ],
  [
    6,
    'II',
    'habēre',
    'have / иметь',
    ['habēb_or', 'habēbe_ris', 'habēbi_tur'],
    ['habēbi_mur', 'habēbi_minī', 'habēbu_ntur'],
  ],
  [
    13,
    'II',
    'habēre',
    'have / иметь',
    ['', 'habē', ''],
    ['', 'habē_te', ''],
  ],
  [
    14,
    'II',
    'habēre',
    'have / иметь',
    ['', 'habē_re', ''],
    ['', 'habē_minī', ''],
  ],
  [
    1,
    'II',
    'teneō -uī -ntum -ēre',
    'hold / держать',
    ['tene_ō', 'tenē_s', 'tene_t'],
    ['tenē_mus', 'tenē_tis', 'tene_nt'],
  ],
  [
    2,
    'II',
    'teneō -uī -ntum -ēre',
    'hold / держать',
    ['tene_or', 'tenē_ris', 'tenē_tur'],
    ['tenē_mur', 'tenē_minī', 'tene_ntur'],
  ],
  [
    3,
    'II',
    'teneō -uī -ntum -ēre',
    'hold / держать',
    ['tenēba_m', 'tenēbā_s', 'tenēba_t'],
    ['tenēbā_mus', 'tenēbā_tis', 'tenēba_nt'],
  ],
  [
    4,
    'II',
    'teneō -uī -ntum -ēre',
    'hold / держать',
    ['tenēba_r', 'tenēbā_ris', 'tenēbā_tur'],
    ['tenēbā_mur', 'tenēbā_minī', 'tenēba_ntur'],
  ],
  [
    5,
    'II',
    'teneō -uī -ntum -ēre',
    'hold / держать',
    ['tenēb_ō', 'tenēbi_s', 'tenēbi_t'],
    ['tenēbi_mus', 'tenēbi_tis', 'tenēbu_nt'],
  ],
  [
    6,
    'II',
    'teneō -uī -ntum -ēre',
    'hold / держать',
    ['tenēb_or', 'tenēbe_ris', 'tenēbi_tur'],
    ['tenēbi_mur', 'tenēbi_minī', 'tenēbu_ntur'],
  ],
  [
    13,
    'II',
    'teneō -uī -ntum -ēre',
    'hold / держать',
    ['', 'tenē', ''],
    ['', 'tenē_te', ''],
  ],
  [
    14,
    'II',
    'teneō -uī -ntum -ēre',
    'hold / держать',
    ['', 'tenē_re', ''],
    ['', 'tenē_minī', ''],
  ],
  [
    1,
    'II',
    'tergeō -sī -sum -ēre',
    'wipe / протирать',
    ['terge_ō', 'tergē_s', 'terge_t'],
    ['tergē_mus', 'tergē_tis', 'terge_nt'],
  ],
  [
    2,
    'II',
    'tergeō -sī -sum -ēre',
    'wipe / протирать',
    ['terge_or', 'tergē_ris', 'tergē_tur'],
    ['tergē_mur', 'tergē_minī', 'terge_ntur'],
  ],
  [
    3,
    'II',
    'tergeō -sī -sum -ēre',
    'wipe / протирать',
    ['tergēba_m', 'tergēbā_s', 'tergēba_t'],
    ['tergēbā_mus', 'tergēbā_tis', 'tergēba_nt'],
  ],
  [
    4,
    'II',
    'tergeō -sī -sum -ēre',
    'wipe / протирать',
    ['tergēba_r', 'tergēbā_ris', 'tergēbā_tur'],
    ['tergēbā_mur', 'tergēbā_minī', 'tergēba_ntur'],
  ],
  [
    5,
    'II',
    'tergeō -sī -sum -ēre',
    'wipe / протирать',
    ['tergēb_ō', 'tergēbi_s', 'tergēbi_t'],
    ['tergēbi_mus', 'tergēbi_tis', 'tergēbu_nt'],
  ],
  [
    6,
    'II',
    'tergeō -sī -sum -ēre',
    'wipe / протирать',
    ['tergēb_or', 'tergēbe_ris', 'tergēbi_tur'],
    ['tergēbi_mur', 'tergēbi_minī', 'tergēbu_ntur'],
  ],
  [
    13,
    'II',
    'tergeō -sī -sum -ēre',
    'wipe / протирать',
    ['', 'tergē', ''],
    ['', 'tergē_te', ''],
  ],
  [
    14,
    'II',
    'tergeō -sī -sum -ēre',
    'wipe / протирать',
    ['', 'tergē_re', ''],
    ['', 'tergē_minī', ''],
  ],
  [
    1,
    'II',
    'moveō mōvī mōtum -ēre',
    'move / двигать',
    ['move_ō', 'movē_s', 'move_t'],
    ['movē_mus', 'movē_tis', 'move_nt'],
  ],
  [
    2,
    'II',
    'moveō mōvī mōtum -ēre',
    'move / двигать',
    ['move_or', 'movē_ris', 'movē_tur'],
    ['movē_mur', 'movē_minī', 'move_ntur'],
  ],
  [
    3,
    'II',
    'moveō mōvī mōtum -ēre',
    'move / двигать',
    ['movēba_m', 'movēbā_s', 'movēba_t'],
    ['movēbā_mus', 'movēbā_tis', 'movēba_nt'],
  ],
  [
    4,
    'II',
    'moveō mōvī mōtum -ēre',
    'move / двигать',
    ['movēba_r', 'movēbā_ris', 'movēbā_tur'],
    ['movēbā_mur', 'movēbā_minī', 'movēba_ntur'],
  ],
  [
    5,
    'II',
    'moveō mōvī mōtum -ēre',
    'move / двигать',
    ['movēb_ō', 'movēbi_s', 'movēbi_t'],
    ['movēbi_mus', 'movēbi_tis', 'movēbu_nt'],
  ],
  [
    6,
    'II',
    'moveō mōvī mōtum -ēre',
    'move / двигать',
    ['movēb_or', 'movēbe_ris', 'movēbi_tur'],
    ['movēbi_mur', 'movēbi_minī', 'movēbu_ntur'],
  ],
  [
    13,
    'II',
    'moveō mōvī mōtum -ēre',
    'move / двигать',
    ['', 'movē', ''],
    ['', 'movē_te', ''],
  ],
  [
    14,
    'II',
    'moveō mōvī mōtum -ēre',
    'move / двигать',
    ['', 'movē_re', ''],
    ['', 'movē_minī', ''],
  ],
  [
    1,
    'II',
    'torreō -uī tostum -ēre',
    'dry, parch / сушить, жечь',
    ['torre_ō', 'torrē_s', 'torre_t'],
    ['torrē_mus', 'torrē_tis', 'torre_nt'],
  ],
  [
    2,
    'II',
    'torreō -uī tostum -ēre',
    'dry, parch / сушить, жечь',
    ['torre_or', 'torrē_ris', 'torrē_tur'],
    ['torrē_mur', 'torrē_minī', 'torre_ntur'],
  ],
  [
    3,
    'II',
    'torreō -uī tostum -ēre',
    'dry, parch / сушить, жечь',
    ['torrēba_m', 'torrēbā_s', 'torrēba_t'],
    ['torrēbā_mus', 'torrēbā_tis', 'torrēba_nt'],
  ],
  [
    4,
    'II',
    'torreō -uī tostum -ēre',
    'dry, parch / сушить, жечь',
    ['torrēba_r', 'torrēbā_ris', 'torrēbā_tur'],
    ['torrēbā_mur', 'torrēbā_minī', 'torrēba_ntur'],
  ],
  [
    5,
    'II',
    'torreō -uī tostum -ēre',
    'dry, parch / сушить, жечь',
    ['torrēb_ō', 'torrēbi_s', 'torrēbi_t'],
    ['torrēbi_mus', 'torrēbi_tis', 'torrēbu_nt'],
  ],
  [
    6,
    'II',
    'torreō -uī tostum -ēre',
    'dry, parch / сушить, жечь',
    ['torrēb_or', 'torrēbe_ris', 'torrēbi_tur'],
    ['torrēbi_mur', 'torrēbi_minī', 'torrēbu_ntur'],
  ],
  [
    13,
    'II',
    'torreō -uī tostum -ēre',
    'dry, parch / сушить, жечь',
    ['', 'torrē', ''],
    ['', 'torrē_te', ''],
  ],
  [
    14,
    'II',
    'torreō -uī tostum -ēre',
    'dry, parch / сушить, жечь',
    ['', 'torrē_re', ''],
    ['', 'torrē_minī', ''],
  ],
  [
    1,
    'II',
    'foveō fōvī fōtum -ēre',
    'keep warm / согревать',
    ['fove_ō', 'fovē_s', 'fove_t'],
    ['fovē_mus', 'fovē_tis', 'fove_nt'],
  ],
  [
    2,
    'II',
    'foveō fōvī fōtum -ēre',
    'keep warm / согревать',
    ['fove_or', 'fovē_ris', 'fovē_tur'],
    ['fovē_mur', 'fovē_minī', 'fove_ntur'],
  ],
  [
    3,
    'II',
    'foveō fōvī fōtum -ēre',
    'keep warm / согревать',
    ['fovēba_m', 'fovēbā_s', 'fovēba_t'],
    ['fovēbā_mus', 'fovēbā_tis', 'fovēba_nt'],
  ],
  [
    4,
    'II',
    'foveō fōvī fōtum -ēre',
    'keep warm / согревать',
    ['fovēba_r', 'fovēbā_ris', 'fovēbā_tur'],
    ['fovēbā_mur', 'fovēbā_minī', 'fovēba_ntur'],
  ],
  [
    5,
    'II',
    'foveō fōvī fōtum -ēre',
    'keep warm / согревать',
    ['fovēb_ō', 'fovēbi_s', 'fovēbi_t'],
    ['fovēbi_mus', 'fovēbi_tis', 'fovēbu_nt'],
  ],
  [
    6,
    'II',
    'foveō fōvī fōtum -ēre',
    'keep warm / согревать',
    ['fovēb_or', 'fovēbe_ris', 'fovēbi_tur'],
    ['fovēbi_mur', 'fovēbi_minī', 'fovēbu_ntur'],
  ],
  [
    13,
    'II',
    'foveō fōvī fōtum -ēre',
    'keep warm / согревать',
    ['', 'fovē', ''],
    ['', 'fovē_te', ''],
  ],
  [
    14,
    'II',
    'foveō fōvī fōtum -ēre',
    'keep warm / согревать',
    ['', 'fovē_re', ''],
    ['', 'fovē_minī', ''],
  ],
  [
    1,
    'II',
    'compleō -ēvī -ētum -ēre',
    'fill up / заполнять',
    ['comple_ō', 'complē_s', 'comple_t'],
    ['complē_mus', 'complē_tis', 'comple_nt'],
  ],
  [
    2,
    'II',
    'compleō -ēvī -ētum -ēre',
    'fill up / заполнять',
    ['comple_or', 'complē_ris', 'complē_tur'],
    ['complē_mur', 'complē_minī', 'comple_ntur'],
  ],
  [
    3,
    'II',
    'compleō -ēvī -ētum -ēre',
    'fill up / заполнять',
    ['complēba_m', 'complēbā_s', 'complēba_t'],
    ['complēbā_mus', 'complēbā_tis', 'complēba_nt'],
  ],
  [
    4,
    'II',
    'compleō -ēvī -ētum -ēre',
    'fill up / заполнять',
    ['complēba_r', 'complēbā_ris', 'complēbā_tur'],
    ['complēbā_mur', 'complēbā_minī', 'complēba_ntur'],
  ],
  [
    5,
    'II',
    'compleō -ēvī -ētum -ēre',
    'fill up / заполнять',
    ['complēb_ō', 'complēbi_s', 'complēbi_t'],
    ['complēbi_mus', 'complēbi_tis', 'complēbu_nt'],
  ],
  [
    6,
    'II',
    'compleō -ēvī -ētum -ēre',
    'fill up / заполнять',
    ['complēb_or', 'complēbe_ris', 'complēbi_tur'],
    ['complēbi_mur', 'complēbi_minī', 'complēbu_ntur'],
  ],
  [
    13,
    'II',
    'compleō -ēvī -ētum -ēre',
    'fill up / заполнять',
    ['', 'complē', ''],
    ['', 'complē_te', ''],
  ],
  [
    14,
    'II',
    'compleō -ēvī -ētum -ēre',
    'fill up / заполнять',
    ['', 'complē_re', ''],
    ['', 'complē_minī', ''],
  ],
  [
    1,
    'II',
    'arcēre',
    'hold off / (у, с)держивать',
    ['arce_ō', 'arcē_s', 'arce_t'],
    ['arcē_mus', 'arcē_tis', 'arce_nt'],
  ],
  [
    2,
    'II',
    'arcēre',
    'hold off / (у, с)держивать',
    ['arce_or', 'arcē_ris', 'arcē_tur'],
    ['arcē_mur', 'arcē_minī', 'arce_ntur'],
  ],
  [
    3,
    'II',
    'arcēre',
    'hold off / (у, с)держивать',
    ['arcēba_m', 'arcēbā_s', 'arcēba_t'],
    ['arcēbā_mus', 'arcēbā_tis', 'arcēba_nt'],
  ],
  [
    4,
    'II',
    'arcēre',
    'hold off / (у, с)держивать',
    ['arcēba_r', 'arcēbā_ris', 'arcēbā_tur'],
    ['arcēbā_mur', 'arcēbā_minī', 'arcēba_ntur'],
  ],
  [
    5,
    'II',
    'arcēre',
    'hold off / (у, с)держивать',
    ['arcēb_ō', 'arcēbi_s', 'arcēbi_t'],
    ['arcēbi_mus', 'arcēbi_tis', 'arcēbu_nt'],
  ],
  [
    6,
    'II',
    'arcēre',
    'hold off / (у, с)держивать',
    ['arcēb_or', 'arcēbe_ris', 'arcēbi_tur'],
    ['arcēbi_mur', 'arcēbi_minī', 'arcēbu_ntur'],
  ],
  [
    13,
    'II',
    'arcēre',
    'hold off / (у, с)держивать',
    ['', 'arcē', ''],
    ['', 'arcē_te', ''],
  ],
  [
    14,
    'II',
    'arcēre',
    'hold off / (у, с)держивать',
    ['', 'arcē_re', ''],
    ['', 'arcē_minī', ''],
  ],
  [
    1,
    'III a',
    'sūmō sūmpsī sūmptum -ere',
    'take / брать',
    ['sūm_ō', 'sūmi_s', 'sūmi_t'],
    ['sūmi_mus', 'sūmi_tis', 'sūmu_nt'],
  ],
  [
    2,
    'III a',
    'sūmō sūmpsī sūmptum -ere',
    'take / брать',
    ['sūm_or', 'sūme_ris', 'sūmi_tur'],
    ['sūmi_mur', 'sūmi_minī', 'sūmu_ntur'],
  ],
  [
    3,
    'III a',
    'sūmō sūmpsī sūmptum -ere',
    'take / брать',
    ['sūmēba_m', 'sūmēbā_s', 'sūmēba_t'],
    ['sūmēbā_mus', 'sūmēbā_tis', 'sūmēba_nt'],
  ],
  [
    4,
    'III a',
    'sūmō sūmpsī sūmptum -ere',
    'take / брать',
    ['sūmēba_r', 'sūmēbā_ris', 'sūmēbā_tur'],
    ['sūmēbā_mur', 'sūmēbā_minī', 'sūmēba_ntur'],
  ],
  [
    5,
    'III a',
    'sūmō sūmpsī sūmptum -ere',
    'take / брать',
    ['sūma_m', 'sūmē_s', 'sūme_t'],
    ['sūmē_mus', 'sūmē_tis', 'sūme_nt'],
  ],
  [
    6,
    'III a',
    'sūmō sūmpsī sūmptum -ere',
    'take / брать',
    ['sūma_r', 'sūmē_ris', 'sūmē_tur'],
    ['sūmē_mur', 'sūmē_minī', 'sūme_ntur'],
  ],
  [
    13,
    'III a',
    'sūmō sūmpsī sūmptum -ere',
    'take / брать',
    ['', 'sūme', ''],
    ['', 'sūmi_te', ''],
  ],
  [
    14,
    'III a',
    'sūmō sūmpsī sūmptum -ere',
    'take / брать',
    ['', 'sūme_re', ''],
    ['', 'sūmi_minī', ''],
  ],
  [
    1,
    'III a',
    'agō ēgī āctum -ere',
    'do / делать',
    ['ag_ō', 'agi_s', 'agi_t'],
    ['agi_mus', 'agi_tis', 'agu_nt'],
  ],
  [
    2,
    'III a',
    'agō ēgī āctum -ere',
    'do / делать',
    ['ag_or', 'age_ris', 'agi_tur'],
    ['agi_mur', 'agi_minī', 'agu_ntur'],
  ],
  [
    3,
    'III a',
    'agō ēgī āctum -ere',
    'do / делать',
    ['agēba_m', 'agēbā_s', 'agēba_t'],
    ['agēbā_mus', 'agēbā_tis', 'agēba_nt'],
  ],
  [
    4,
    'III a',
    'agō ēgī āctum -ere',
    'do / делать',
    ['agēba_r', 'agēbā_ris', 'agēbā_tur'],
    ['agēbā_mur', 'agēbā_minī', 'agēba_ntur'],
  ],
  [
    5,
    'III a',
    'agō ēgī āctum -ere',
    'do / делать',
    ['aga_m', 'agē_s', 'age_t'],
    ['agē_mus', 'agē_tis', 'age_nt'],
  ],
  [
    6,
    'III a',
    'agō ēgī āctum -ere',
    'do / делать',
    ['aga_r', 'agē_ris', 'agē_tur'],
    ['agē_mur', 'agē_minī', 'age_ntur'],
  ],
  [
    13,
    'III a',
    'agō ēgī āctum -ere',
    'do / делать',
    ['', 'age', ''],
    ['', 'agi_te', ''],
  ],
  [
    14,
    'III a',
    'agō ēgī āctum -ere',
    'do / делать',
    ['', 'age_re', ''],
    ['', 'agi_minī', ''],
  ],
  [
    1,
    'III a',
    'vehō vexī vectum -ere',
    'carry, convey / нести, везти',
    ['veh_ō', 'vehi_s', 'vehi_t'],
    ['vehi_mus', 'vehi_tis', 'vehu_nt'],
  ],
  [
    2,
    'III a',
    'vehō vexī vectum -ere',
    'carry, convey / нести, везти',
    ['veh_or', 'vehe_ris', 'vehi_tur'],
    ['vehi_mur', 'vehi_minī', 'vehu_ntur'],
  ],
  [
    3,
    'III a',
    'vehō vexī vectum -ere',
    'carry, convey / нести, везти',
    ['vehēba_m', 'vehēbā_s', 'vehēba_t'],
    ['vehēbā_mus', 'vehēbā_tis', 'vehēba_nt'],
  ],
  [
    4,
    'III a',
    'vehō vexī vectum -ere',
    'carry, convey / нести, везти',
    ['vehēba_r', 'vehēbā_ris', 'vehēbā_tur'],
    ['vehēbā_mur', 'vehēbā_minī', 'vehēba_ntur'],
  ],
  [
    5,
    'III a',
    'vehō vexī vectum -ere',
    'carry, convey / нести, везти',
    ['veha_m', 'vehē_s', 'vehe_t'],
    ['vehē_mus', 'vehē_tis', 'vehe_nt'],
  ],
  [
    6,
    'III a',
    'vehō vexī vectum -ere',
    'carry, convey / нести, везти',
    ['veha_r', 'vehē_ris', 'vehē_tur'],
    ['vehē_mur', 'vehē_minī', 'vehe_ntur'],
  ],
  [
    13,
    'III a',
    'vehō vexī vectum -ere',
    'carry, convey / нести, везти',
    ['', 'vehe', ''],
    ['', 'vehi_te', ''],
  ],
  [
    14,
    'III a',
    'vehō vexī vectum -ere',
    'carry, convey / нести, везти',
    ['', 'vehe_re', ''],
    ['', 'vehi_minī', ''],
  ],
  [
    1,
    'III a',
    'vertō -sī -sum -ere',
    'turn / вертеть, поворачивать',
    ['vert_ō', 'verti_s', 'verti_t'],
    ['verti_mus', 'verti_tis', 'vertu_nt'],
  ],
  [
    2,
    'III a',
    'vertō -sī -sum -ere',
    'turn / вертеть, поворачивать',
    ['vert_or', 'verte_ris', 'verti_tur'],
    ['verti_mur', 'verti_minī', 'vertu_ntur'],
  ],
  [
    3,
    'III a',
    'vertō -sī -sum -ere',
    'turn / вертеть, поворачивать',
    ['vertēba_m', 'vertēbā_s', 'vertēba_t'],
    ['vertēbā_mus', 'vertēbā_tis', 'vertēba_nt'],
  ],
  [
    4,
    'III a',
    'vertō -sī -sum -ere',
    'turn / вертеть, поворачивать',
    ['vertēba_r', 'vertēbā_ris', 'vertēbā_tur'],
    ['vertēbā_mur', 'vertēbā_minī', 'vertēba_ntur'],
  ],
  [
    5,
    'III a',
    'vertō -sī -sum -ere',
    'turn / вертеть, поворачивать',
    ['verta_m', 'vertē_s', 'verte_t'],
    ['vertē_mus', 'vertē_tis', 'verte_nt'],
  ],
  [
    6,
    'III a',
    'vertō -sī -sum -ere',
    'turn / вертеть, поворачивать',
    ['verta_r', 'vertē_ris', 'vertē_tur'],
    ['vertē_mur', 'vertē_minī', 'verte_ntur'],
  ],
  [
    13,
    'III a',
    'vertō -sī -sum -ere',
    'turn / вертеть, поворачивать',
    ['', 'verte', ''],
    ['', 'verti_te', ''],
  ],
  [
    14,
    'III a',
    'vertō -sī -sum -ere',
    'turn / вертеть, поворачивать',
    ['', 'verte_re', ''],
    ['', 'verti_minī', ''],
  ],
  [
    1,
    'III a',
    'emō ēmī ēmptum -ere',
    'buy / покупать',
    ['em_ō', 'emi_s', 'emi_t'],
    ['emi_mus', 'emi_tis', 'emu_nt'],
  ],
  [
    2,
    'III a',
    'emō ēmī ēmptum -ere',
    'buy / покупать',
    ['em_or', 'eme_ris', 'emi_tur'],
    ['emi_mur', 'emi_minī', 'emu_ntur'],
  ],
  [
    3,
    'III a',
    'emō ēmī ēmptum -ere',
    'buy / покупать',
    ['emēba_m', 'emēbā_s', 'emēba_t'],
    ['emēbā_mus', 'emēbā_tis', 'emēba_nt'],
  ],
  [
    4,
    'III a',
    'emō ēmī ēmptum -ere',
    'buy / покупать',
    ['emēba_r', 'emēbā_ris', 'emēbā_tur'],
    ['emēbā_mur', 'emēbā_minī', 'emēba_ntur'],
  ],
  [
    5,
    'III a',
    'emō ēmī ēmptum -ere',
    'buy / покупать',
    ['ema_m', 'emē_s', 'eme_t'],
    ['emē_mus', 'emē_tis', 'eme_nt'],
  ],
  [
    6,
    'III a',
    'emō ēmī ēmptum -ere',
    'buy / покупать',
    ['ema_r', 'emē_ris', 'emē_tur'],
    ['emē_mur', 'emē_minī', 'eme_ntur'],
  ],
  [
    13,
    'III a',
    'emō ēmī ēmptum -ere',
    'buy / покупать',
    ['', 'eme', ''],
    ['', 'emi_te', ''],
  ],
  [
    14,
    'III a',
    'emō ēmī ēmptum -ere',
    'buy / покупать',
    ['', 'eme_re', ''],
    ['', 'emi_minī', ''],
  ],
  [
    1,
    'III a',
    'dūcō dūxī ductum -ere',
    'lead / вести',
    ['dūc_ō', 'dūci_s', 'dūci_t'],
    ['dūci_mus', 'dūci_tis', 'dūcu_nt'],
  ],
  [
    2,
    'III a',
    'dūcō dūxī ductum -ere',
    'lead / вести',
    ['dūc_or', 'dūce_ris', 'dūci_tur'],
    ['dūci_mur', 'dūci_minī', 'dūcu_ntur'],
  ],
  [
    3,
    'III a',
    'dūcō dūxī ductum -ere',
    'lead / вести',
    ['dūcēba_m', 'dūcēbā_s', 'dūcēba_t'],
    ['dūcēbā_mus', 'dūcēbā_tis', 'dūcēba_nt'],
  ],
  [
    4,
    'III a',
    'dūcō dūxī ductum -ere',
    'lead / вести',
    ['dūcēba_r', 'dūcēbā_ris', 'dūcēbā_tur'],
    ['dūcēbā_mur', 'dūcēbā_minī', 'dūcēba_ntur'],
  ],
  [
    5,
    'III a',
    'dūcō dūxī ductum -ere',
    'lead / вести',
    ['dūca_m', 'dūcē_s', 'dūce_t'],
    ['dūcē_mus', 'dūcē_tis', 'dūce_nt'],
  ],
  [
    6,
    'III a',
    'dūcō dūxī ductum -ere',
    'lead / вести',
    ['dūca_r', 'dūcē_ris', 'dūcē_tur'],
    ['dūcē_mur', 'dūcē_minī', 'dūce_ntur'],
  ],
  [
    13,
    'III a',
    'dūcō dūxī ductum -ere',
    'lead / вести',
    ['', 'dūce', ''],
    ['', 'dūci_te', ''],
  ],
  [
    14,
    'III a',
    'dūcō dūxī ductum -ere',
    'lead / вести',
    ['', 'dūce_re', ''],
    ['', 'dūci_minī', ''],
  ],
  [
    1,
    'III a',
    'crēdō -didī -ditum -ere',
    'believe / верить',
    ['crēd_ō', 'crēdi_s', 'crēdi_t'],
    ['crēdi_mus', 'crēdi_tis', 'crēdu_nt'],
  ],
  [
    2,
    'III a',
    'crēdō -didī -ditum -ere',
    'believe / верить',
    ['crēd_or', 'crēde_ris', 'crēdi_tur'],
    ['crēdi_mur', 'crēdi_minī', 'crēdu_ntur'],
  ],
  [
    3,
    'III a',
    'crēdō -didī -ditum -ere',
    'believe / верить',
    ['crēdēba_m', 'crēdēbā_s', 'crēdēba_t'],
    ['crēdēbā_mus', 'crēdēbā_tis', 'crēdēba_nt'],
  ],
  [
    4,
    'III a',
    'crēdō -didī -ditum -ere',
    'believe / верить',
    ['crēdēba_r', 'crēdēbā_ris', 'crēdēbā_tur'],
    ['crēdēbā_mur', 'crēdēbā_minī', 'crēdēba_ntur'],
  ],
  [
    5,
    'III a',
    'crēdō -didī -ditum -ere',
    'believe / верить',
    ['crēda_m', 'crēdē_s', 'crēde_t'],
    ['crēdē_mus', 'crēdē_tis', 'crēde_nt'],
  ],
  [
    6,
    'III a',
    'crēdō -didī -ditum -ere',
    'believe / верить',
    ['crēda_r', 'crēdē_ris', 'crēdē_tur'],
    ['crēdē_mur', 'crēdē_minī', 'crēde_ntur'],
  ],
  [
    13,
    'III a',
    'crēdō -didī -ditum -ere',
    'believe / верить',
    ['', 'crēde', ''],
    ['', 'crēdi_te', ''],
  ],
  [
    14,
    'III a',
    'crēdō -didī -ditum -ere',
    'believe / верить',
    ['', 'crēde_re', ''],
    ['', 'crēdi_minī', ''],
  ],
  [
    1,
    'III a',
    'lūdō -sī -sum -ere',
    'play / играть',
    ['lūd_ō', 'lūdi_s', 'lūdi_t'],
    ['lūdi_mus', 'lūdi_tis', 'lūdu_nt'],
  ],
  [
    2,
    'III a',
    'lūdō -sī -sum -ere',
    'play / играть',
    ['lūd_or', 'lūde_ris', 'lūdi_tur'],
    ['lūdi_mur', 'lūdi_minī', 'lūdu_ntur'],
  ],
  [
    3,
    'III a',
    'lūdō -sī -sum -ere',
    'play / играть',
    ['lūdēba_m', 'lūdēbā_s', 'lūdēba_t'],
    ['lūdēbā_mus', 'lūdēbā_tis', 'lūdēba_nt'],
  ],
  [
    4,
    'III a',
    'lūdō -sī -sum -ere',
    'play / играть',
    ['lūdēba_r', 'lūdēbā_ris', 'lūdēbā_tur'],
    ['lūdēbā_mur', 'lūdēbā_minī', 'lūdēba_ntur'],
  ],
  [
    5,
    'III a',
    'lūdō -sī -sum -ere',
    'play / играть',
    ['lūda_m', 'lūdē_s', 'lūde_t'],
    ['lūdē_mus', 'lūdē_tis', 'lūde_nt'],
  ],
  [
    6,
    'III a',
    'lūdō -sī -sum -ere',
    'play / играть',
    ['lūda_r', 'lūdē_ris', 'lūdē_tur'],
    ['lūdē_mur', 'lūdē_minī', 'lūde_ntur'],
  ],
  [
    13,
    'III a',
    'lūdō -sī -sum -ere',
    'play / играть',
    ['', 'lūde', ''],
    ['', 'lūdi_te', ''],
  ],
  [
    14,
    'III a',
    'lūdō -sī -sum -ere',
    'play / играть',
    ['', 'lūde_re', ''],
    ['', 'lūdi_minī', ''],
  ],
  [
    1,
    'III a',
    'tollō sustulī sublātum -ere',
    'lift, raise / поднимать',
    ['toll_ō', 'tolli_s', 'tolli_t'],
    ['tolli_mus', 'tolli_tis', 'tollu_nt'],
  ],
  [
    2,
    'III a',
    'tollō sustulī sublātum -ere',
    'lift, raise / поднимать',
    ['toll_or', 'tolle_ris', 'tolli_tur'],
    ['tolli_mur', 'tolli_minī', 'tollu_ntur'],
  ],
  [
    3,
    'III a',
    'tollō sustulī sublātum -ere',
    'lift, raise / поднимать',
    ['tollēba_m', 'tollēbā_s', 'tollēba_t'],
    ['tollēbā_mus', 'tollēbā_tis', 'tollēba_nt'],
  ],
  [
    4,
    'III a',
    'tollō sustulī sublātum -ere',
    'lift, raise / поднимать',
    ['tollēba_r', 'tollēbā_ris', 'tollēbā_tur'],
    ['tollēbā_mur', 'tollēbā_minī', 'tollēba_ntur'],
  ],
  [
    5,
    'III a',
    'tollō sustulī sublātum -ere',
    'lift, raise / поднимать',
    ['tolla_m', 'tollē_s', 'tolle_t'],
    ['tollē_mus', 'tollē_tis', 'tolle_nt'],
  ],
  [
    6,
    'III a',
    'tollō sustulī sublātum -ere',
    'lift, raise / поднимать',
    ['tolla_r', 'tollē_ris', 'tollē_tur'],
    ['tollē_mur', 'tollē_minī', 'tolle_ntur'],
  ],
  [
    13,
    'III a',
    'tollō sustulī sublātum -ere',
    'lift, raise / поднимать',
    ['', 'tolle', ''],
    ['', 'tolli_te', ''],
  ],
  [
    14,
    'III a',
    'tollō sustulī sublātum -ere',
    'lift, raise / поднимать',
    ['', 'tolle_re', ''],
    ['', 'tolli_minī', ''],
  ],
  [
    1,
    'III a',
    'fallō fefellī falsum -ere',
    'deceive / обманывать',
    ['fall_ō', 'falli_s', 'falli_t'],
    ['falli_mus', 'falli_tis', 'fallu_nt'],
  ],
  [
    2,
    'III a',
    'fallō fefellī falsum -ere',
    'deceive / обманывать',
    ['fall_or', 'falle_ris', 'falli_tur'],
    ['falli_mur', 'falli_minī', 'fallu_ntur'],
  ],
  [
    3,
    'III a',
    'fallō fefellī falsum -ere',
    'deceive / обманывать',
    ['fallēba_m', 'fallēbā_s', 'fallēba_t'],
    ['fallēbā_mus', 'fallēbā_tis', 'fallēba_nt'],
  ],
  [
    4,
    'III a',
    'fallō fefellī falsum -ere',
    'deceive / обманывать',
    ['fallēba_r', 'fallēbā_ris', 'fallēbā_tur'],
    ['fallēbā_mur', 'fallēbā_minī', 'fallēba_ntur'],
  ],
  [
    5,
    'III a',
    'fallō fefellī falsum -ere',
    'deceive / обманывать',
    ['falla_m', 'fallē_s', 'falle_t'],
    ['fallē_mus', 'fallē_tis', 'falle_nt'],
  ],
  [
    6,
    'III a',
    'fallō fefellī falsum -ere',
    'deceive / обманывать',
    ['falla_r', 'fallē_ris', 'fallē_tur'],
    ['fallē_mur', 'fallē_minī', 'falle_ntur'],
  ],
  [
    13,
    'III a',
    'fallō fefellī falsum -ere',
    'deceive / обманывать',
    ['', 'falle', ''],
    ['', 'falli_te', ''],
  ],
  [
    14,
    'III a',
    'fallō fefellī falsum -ere',
    'deceive / обманывать',
    ['', 'falle_re', ''],
    ['', 'falli_minī', ''],
  ],
  [
    1,
    'III b',
    'faciō fēcī factum -ere',
    'make / делать',
    ['faci_ō', 'faci_s', 'faci_t'],
    ['faci_mus', 'faci_tis', 'faciu_nt'],
  ],
  [
    2,
    'III b',
    'faciō fēcī factum -ere',
    'make / делать',
    ['fī_ō', 'fī_s', 'fi_t'],
    ['fī_mus', 'fī_tis', 'fīu_nt'],
  ],
  [
    3,
    'III b',
    'faciō fēcī factum -ere',
    'make / делать',
    ['faciēba_m', 'faciēbā_s', 'faciēba_t'],
    ['faciēbā_mus', 'faciēbā_tis', 'faciēba_nt'],
  ],
  [
    4,
    'III b',
    'faciō fēcī factum -ere',
    'make / делать',
    ['fīēba_m', 'fīēbā_s', 'fīēba_t'],
    ['fīēbā_mus', 'fīēbā_tis', 'fīēba_nt'],
  ],
  [
    5,
    'III b',
    'faciō fēcī factum -ere',
    'make / делать',
    ['facia_m', 'faciē_s', 'facie_t'],
    ['faciē_mus', 'faciē_tis', 'facie_nt'],
  ],
  [
    6,
    'III b',
    'faciō fēcī factum -ere',
    'make / делать',
    ['facia_r', 'faciē_ris', 'faciē_tur'],
    ['faciē_mur', 'faciē_minī', 'facie_ntur'],
  ],
  [
    13,
    'III b',
    'faciō fēcī factum -ere',
    'make / делать',
    ['', 'face', ''],
    ['', 'faci_te', ''],
  ],
  [
    14,
    'III b',
    'faciō fēcī factum -ere',
    'make / делать',
    ['', 'fī', ''],
    ['', 'fī_te', ''],
  ],
  [
    1,
    'III b',
    'capiō cēpī captum -ere',
    'take, take hold of / брать, хватать',
    ['capi_ō', 'capi_s', 'capi_t'],
    ['capi_mus', 'capi_tis', 'capiu_nt'],
  ],
  [
    2,
    'III b',
    'capiō cēpī captum -ere',
    'take, take hold of / брать, хватать',
    ['capi_or', 'cape_ris', 'capi_tur'],
    ['capi_mur', 'capi_minī', 'capiu_ntur'],
  ],
  [
    3,
    'III b',
    'capiō cēpī captum -ere',
    'take, take hold of / брать, хватать',
    ['capiēba_m', 'capiēbā_s', 'capiēba_t'],
    ['capiēbā_mus', 'capiēbā_tis', 'capiēba_nt'],
  ],
  [
    4,
    'III b',
    'capiō cēpī captum -ere',
    'take, take hold of / брать, хватать',
    ['capiēba_r', 'capiēbā_ris', 'capiēbā_tur'],
    ['capiēbā_mur', 'capiēbā_minī', 'capiēba_ntur'],
  ],
  [
    5,
    'III b',
    'capiō cēpī captum -ere',
    'take, take hold of / брать, хватать',
    ['capia_m', 'capiē_s', 'capie_t'],
    ['capiē_mus', 'capiē_tis', 'capie_nt'],
  ],
  [
    6,
    'III b',
    'capiō cēpī captum -ere',
    'take, take hold of / брать, хватать',
    ['capia_r', 'capiē_ris', 'capiē_tur'],
    ['capiē_mur', 'capiē_minī', 'capie_ntur'],
  ],
  [
    13,
    'III b',
    'capiō cēpī captum -ere',
    'take, take hold of / брать, хватать',
    ['', 'cape', ''],
    ['', 'capi_te', ''],
  ],
  [
    14,
    'III b',
    'capiō cēpī captum -ere',
    'take, take hold of / брать, хватать',
    ['', 'cape_re', ''],
    ['', 'capi_minī', ''],
  ],
  [
    1,
    'III b',
    'iaciō iēcī iactum -ere',
    'throw / кидать',
    ['iaci_ō', 'iaci_s', 'iaci_t'],
    ['iaci_mus', 'iaci_tis', 'iaciu_nt'],
  ],
  [
    2,
    'III b',
    'iaciō iēcī iactum -ere',
    'throw / кидать',
    ['iaci_or', 'iace_ris', 'iaci_tur'],
    ['iaci_mur', 'iaci_minī', 'iaciu_ntur'],
  ],
  [
    3,
    'III b',
    'iaciō iēcī iactum -ere',
    'throw / кидать',
    ['iaciēba_m', 'iaciēbā_s', 'iaciēba_t'],
    ['iaciēbā_mus', 'iaciēbā_tis', 'iaciēba_nt'],
  ],
  [
    4,
    'III b',
    'iaciō iēcī iactum -ere',
    'throw / кидать',
    ['iaciēba_r', 'iaciēbā_ris', 'iaciēbā_tur'],
    ['iaciēbā_mur', 'iaciēbā_minī', 'iaciēba_ntur'],
  ],
  [
    5,
    'III b',
    'iaciō iēcī iactum -ere',
    'throw / кидать',
    ['iacia_m', 'iaciē_s', 'iacie_t'],
    ['iaciē_mus', 'iaciē_tis', 'iacie_nt'],
  ],
  [
    6,
    'III b',
    'iaciō iēcī iactum -ere',
    'throw / кидать',
    ['iacia_r', 'iaciē_ris', 'iaciē_tur'],
    ['iaciē_mur', 'iaciē_minī', 'iacie_ntur'],
  ],
  [
    13,
    'III b',
    'iaciō iēcī iactum -ere',
    'throw / кидать',
    ['', 'iace', ''],
    ['', 'iaci_te', ''],
  ],
  [
    14,
    'III b',
    'iaciō iēcī iactum -ere',
    'throw / кидать',
    ['', 'iace_re', ''],
    ['', 'iaci_minī', ''],
  ],
  [
    1,
    'III b',
    'aspiciō -spexī -spectum -ere',
    'look / глядеть',
    ['aspici_ō', 'aspici_s', 'aspici_t'],
    ['aspici_mus', 'aspici_tis', 'aspiciu_nt'],
  ],
  [
    2,
    'III b',
    'aspiciō -spexī -spectum -ere',
    'look / глядеть',
    ['aspici_or', 'aspice_ris', 'aspici_tur'],
    ['aspici_mur', 'aspici_minī', 'aspiciu_ntur'],
  ],
  [
    3,
    'III b',
    'aspiciō -spexī -spectum -ere',
    'look / глядеть',
    ['aspiciēba_m', 'aspiciēbā_s', 'aspiciēba_t'],
    ['aspiciēbā_mus', 'aspiciēbā_tis', 'aspiciēba_nt'],
  ],
  [
    4,
    'III b',
    'aspiciō -spexī -spectum -ere',
    'look / глядеть',
    ['aspiciēba_r', 'aspiciēbā_ris', 'aspiciēbā_tur'],
    ['aspiciēbā_mur', 'aspiciēbā_minī', 'aspiciēba_ntur'],
  ],
  [
    5,
    'III b',
    'aspiciō -spexī -spectum -ere',
    'look / глядеть',
    ['aspicia_m', 'aspiciē_s', 'aspicie_t'],
    ['aspiciē_mus', 'aspiciē_tis', 'aspicie_nt'],
  ],
  [
    6,
    'III b',
    'aspiciō -spexī -spectum -ere',
    'look / глядеть',
    ['aspicia_r', 'aspiciē_ris', 'aspiciē_tur'],
    ['aspiciē_mur', 'aspiciē_minī', 'aspicie_ntur'],
  ],
  [
    13,
    'III b',
    'aspiciō -spexī -spectum -ere',
    'look / глядеть',
    ['', 'aspice', ''],
    ['', 'aspici_te', ''],
  ],
  [
    14,
    'III b',
    'aspiciō -spexī -spectum -ere',
    'look / глядеть',
    ['', 'aspice_re', ''],
    ['', 'aspici_minī', ''],
  ],
  [
    1,
    'III b',
    'accipiō -cēpī -ceptum -ere',
    'accept / принимать',
    ['accipi_ō', 'accipi_s', 'accipi_t'],
    ['accipi_mus', 'accipi_tis', 'accipiu_nt'],
  ],
  [
    2,
    'III b',
    'accipiō -cēpī -ceptum -ere',
    'accept / принимать',
    ['accipi_or', 'accipe_ris', 'accipi_tur'],
    ['accipi_mur', 'accipi_minī', 'accipiu_ntur'],
  ],
  [
    3,
    'III b',
    'accipiō -cēpī -ceptum -ere',
    'accept / принимать',
    ['accipiēba_m', 'accipiēbā_s', 'accipiēba_t'],
    ['accipiēbā_mus', 'accipiēbā_tis', 'accipiēba_nt'],
  ],
  [
    4,
    'III b',
    'accipiō -cēpī -ceptum -ere',
    'accept / принимать',
    ['accipiēba_r', 'accipiēbā_ris', 'accipiēbā_tur'],
    ['accipiēbā_mur', 'accipiēbā_minī', 'accipiēba_ntur'],
  ],
  [
    5,
    'III b',
    'accipiō -cēpī -ceptum -ere',
    'accept / принимать',
    ['accipia_m', 'accipiē_s', 'accipie_t'],
    ['accipiē_mus', 'accipiē_tis', 'accipie_nt'],
  ],
  [
    6,
    'III b',
    'accipiō -cēpī -ceptum -ere',
    'accept / принимать',
    ['accipia_r', 'accipiē_ris', 'accipiē_tur'],
    ['accipiē_mur', 'accipiē_minī', 'accipie_ntur'],
  ],
  [
    13,
    'III b',
    'accipiō -cēpī -ceptum -ere',
    'accept / принимать',
    ['', 'accipe', ''],
    ['', 'accipi_te', ''],
  ],
  [
    14,
    'III b',
    'accipiō -cēpī -ceptum -ere',
    'accept / принимать',
    ['', 'accipe_re', ''],
    ['', 'accipi_minī', ''],
  ],
  [
    1,
    'III b',
    'interficiō -fēcī -fectum -ere',
    'kill / убивать',
    ['interfici_ō', 'interfici_s', 'interfici_t'],
    ['interfici_mus', 'interfici_tis', 'interficiu_nt'],
  ],
  [
    2,
    'III b',
    'interficiō -fēcī -fectum -ere',
    'kill / убивать',
    ['interfici_or', 'interfice_ris', 'interfici_tur'],
    ['interfici_mur', 'interfici_minī', 'interficiu_ntur'],
  ],
  [
    3,
    'III b',
    'interficiō -fēcī -fectum -ere',
    'kill / убивать',
    ['interficiēba_m', 'interficiēbā_s', 'interficiēba_t'],
    ['interficiēbā_mus', 'interficiēbā_tis', 'interficiēba_nt'],
  ],
  [
    4,
    'III b',
    'interficiō -fēcī -fectum -ere',
    'kill / убивать',
    ['interficiēba_r', 'interficiēbā_ris', 'interficiēbā_tur'],
    ['interficiēbā_mur', 'interficiēbā_minī', 'interficiēba_ntur'],
  ],
  [
    5,
    'III b',
    'interficiō -fēcī -fectum -ere',
    'kill / убивать',
    ['interficia_m', 'interficiē_s', 'interficie_t'],
    ['interficiē_mus', 'interficiē_tis', 'interficie_nt'],
  ],
  [
    6,
    'III b',
    'interficiō -fēcī -fectum -ere',
    'kill / убивать',
    ['interficia_r', 'interficiē_ris', 'interficiē_tur'],
    ['interficiē_mur', 'interficiē_minī', 'interficie_ntur'],
  ],
  [
    13,
    'III b',
    'interficiō -fēcī -fectum -ere',
    'kill / убивать',
    ['', 'interfice', ''],
    ['', 'interfici_te', ''],
  ],
  [
    14,
    'III b',
    'interficiō -fēcī -fectum -ere',
    'kill / убивать',
    ['', 'interfice_re', ''],
    ['', 'interfici_minī', ''],
  ],
  [
    1,
    'III b',
    'rapiō -uī raptum -ere',
    'seize; carry off / хватать; похищать',
    ['rapi_ō', 'rapi_s', 'rapi_t'],
    ['rapi_mus', 'rapi_tis', 'rapiu_nt'],
  ],
  [
    2,
    'III b',
    'rapiō -uī raptum -ere',
    'seize; carry off / хватать; похищать',
    ['rapi_or', 'rape_ris', 'rapi_tur'],
    ['rapi_mur', 'rapi_minī', 'rapiu_ntur'],
  ],
  [
    3,
    'III b',
    'rapiō -uī raptum -ere',
    'seize; carry off / хватать; похищать',
    ['rapiēba_m', 'rapiēbā_s', 'rapiēba_t'],
    ['rapiēbā_mus', 'rapiēbā_tis', 'rapiēba_nt'],
  ],
  [
    4,
    'III b',
    'rapiō -uī raptum -ere',
    'seize; carry off / хватать; похищать',
    ['rapiēba_r', 'rapiēbā_ris', 'rapiēbā_tur'],
    ['rapiēbā_mur', 'rapiēbā_minī', 'rapiēba_ntur'],
  ],
  [
    5,
    'III b',
    'rapiō -uī raptum -ere',
    'seize; carry off / хватать; похищать',
    ['rapia_m', 'rapiē_s', 'rapie_t'],
    ['rapiē_mus', 'rapiē_tis', 'rapie_nt'],
  ],
  [
    6,
    'III b',
    'rapiō -uī raptum -ere',
    'seize; carry off / хватать; похищать',
    ['rapia_r', 'rapiē_ris', 'rapiē_tur'],
    ['rapiē_mur', 'rapiē_minī', 'rapie_ntur'],
  ],
  [
    13,
    'III b',
    'rapiō -uī raptum -ere',
    'seize; carry off / хватать; похищать',
    ['', 'rape', ''],
    ['', 'rapi_te', ''],
  ],
  [
    14,
    'III b',
    'rapiō -uī raptum -ere',
    'seize; carry off / хватать; похищать',
    ['', 'rape_re', ''],
    ['', 'rapi_minī', ''],
  ],
  [
    1,
    'III b',
    'cōnficiō -fēcī -fectum -ere',
    'complete / завершать',
    ['cōnfici_ō', 'cōnfici_s', 'cōnfici_t'],
    ['cōnfici_mus', 'cōnfici_tis', 'cōnficiu_nt'],
  ],
  [
    2,
    'III b',
    'cōnficiō -fēcī -fectum -ere',
    'complete / завершать',
    ['cōnfici_or', 'cōnfice_ris', 'cōnfici_tur'],
    ['cōnfici_mur', 'cōnfici_minī', 'cōnficiu_ntur'],
  ],
  [
    3,
    'III b',
    'cōnficiō -fēcī -fectum -ere',
    'complete / завершать',
    ['cōnficiēba_m', 'cōnficiēbā_s', 'cōnficiēba_t'],
    ['cōnficiēbā_mus', 'cōnficiēbā_tis', 'cōnficiēba_nt'],
  ],
  [
    4,
    'III b',
    'cōnficiō -fēcī -fectum -ere',
    'complete / завершать',
    ['cōnficiēba_r', 'cōnficiēbā_ris', 'cōnficiēbā_tur'],
    ['cōnficiēbā_mur', 'cōnficiēbā_minī', 'cōnficiēba_ntur'],
  ],
  [
    5,
    'III b',
    'cōnficiō -fēcī -fectum -ere',
    'complete / завершать',
    ['cōnficia_m', 'cōnficiē_s', 'cōnficie_t'],
    ['cōnficiē_mus', 'cōnficiē_tis', 'cōnficie_nt'],
  ],
  [
    6,
    'III b',
    'cōnficiō -fēcī -fectum -ere',
    'complete / завершать',
    ['cōnficia_r', 'cōnficiē_ris', 'cōnficiē_tur'],
    ['cōnficiē_mur', 'cōnficiē_minī', 'cōnficie_ntur'],
  ],
  [
    13,
    'III b',
    'cōnficiō -fēcī -fectum -ere',
    'complete / завершать',
    ['', 'cōnfice', ''],
    ['', 'cōnfici_te', ''],
  ],
  [
    14,
    'III b',
    'cōnficiō -fēcī -fectum -ere',
    'complete / завершать',
    ['', 'cōnfice_re', ''],
    ['', 'cōnfici_minī', ''],
  ],
  [
    1,
    'III b',
    'afficiō -fēcī -fectum -ere',
    'affect / причинять',
    ['affici_ō', 'affici_s', 'affici_t'],
    ['affici_mus', 'affici_tis', 'afficiu_nt'],
  ],
  [
    2,
    'III b',
    'afficiō -fēcī -fectum -ere',
    'affect / причинять',
    ['affici_or', 'affice_ris', 'affici_tur'],
    ['affici_mur', 'affici_minī', 'afficiu_ntur'],
  ],
  [
    3,
    'III b',
    'afficiō -fēcī -fectum -ere',
    'affect / причинять',
    ['afficiēba_m', 'afficiēbā_s', 'afficiēba_t'],
    ['afficiēbā_mus', 'afficiēbā_tis', 'afficiēba_nt'],
  ],
  [
    4,
    'III b',
    'afficiō -fēcī -fectum -ere',
    'affect / причинять',
    ['afficiēba_r', 'afficiēbā_ris', 'afficiēbā_tur'],
    ['afficiēbā_mur', 'afficiēbā_minī', 'afficiēba_ntur'],
  ],
  [
    5,
    'III b',
    'afficiō -fēcī -fectum -ere',
    'affect / причинять',
    ['afficia_m', 'afficiē_s', 'afficie_t'],
    ['afficiē_mus', 'afficiē_tis', 'afficie_nt'],
  ],
  [
    6,
    'III b',
    'afficiō -fēcī -fectum -ere',
    'affect / причинять',
    ['afficia_r', 'afficiē_ris', 'afficiē_tur'],
    ['afficiē_mur', 'afficiē_minī', 'afficie_ntur'],
  ],
  [
    13,
    'III b',
    'afficiō -fēcī -fectum -ere',
    'affect / причинять',
    ['', 'affice', ''],
    ['', 'affici_te', ''],
  ],
  [
    14,
    'III b',
    'afficiō -fēcī -fectum -ere',
    'affect / причинять',
    ['', 'affice_re', ''],
    ['', 'affici_minī', ''],
  ],
  [
    1,
    'III b',
    'cōnspiciō -spexī -spectum -ere',
    'get sight of / заметить',
    ['cōnspici_ō', 'cōnspici_s', 'cōnspici_t'],
    ['cōnspici_mus', 'cōnspici_tis', 'cōnspiciu_nt'],
  ],
  [
    2,
    'III b',
    'cōnspiciō -spexī -spectum -ere',
    'get sight of / заметить',
    ['cōnspici_or', 'cōnspice_ris', 'cōnspici_tur'],
    ['cōnspici_mur', 'cōnspici_minī', 'cōnspiciu_ntur'],
  ],
  [
    3,
    'III b',
    'cōnspiciō -spexī -spectum -ere',
    'get sight of / заметить',
    ['cōnspiciēba_m', 'cōnspiciēbā_s', 'cōnspiciēba_t'],
    ['cōnspiciēbā_mus', 'cōnspiciēbā_tis', 'cōnspiciēba_nt'],
  ],
  [
    4,
    'III b',
    'cōnspiciō -spexī -spectum -ere',
    'get sight of / заметить',
    ['cōnspiciēba_r', 'cōnspiciēbā_ris', 'cōnspiciēbā_tur'],
    ['cōnspiciēbā_mur', 'cōnspiciēbā_minī', 'cōnspiciēba_ntur'],
  ],
  [
    5,
    'III b',
    'cōnspiciō -spexī -spectum -ere',
    'get sight of / заметить',
    ['cōnspicia_m', 'cōnspiciē_s', 'cōnspicie_t'],
    ['cōnspiciē_mus', 'cōnspiciē_tis', 'cōnspicie_nt'],
  ],
  [
    6,
    'III b',
    'cōnspiciō -spexī -spectum -ere',
    'get sight of / заметить',
    ['cōnspicia_r', 'cōnspiciē_ris', 'cōnspiciē_tur'],
    ['cōnspiciē_mur', 'cōnspiciē_minī', 'cōnspicie_ntur'],
  ],
  [
    13,
    'III b',
    'cōnspiciō -spexī -spectum -ere',
    'get sight of / заметить',
    ['', 'cōnspice', ''],
    ['', 'cōnspici_te', ''],
  ],
  [
    14,
    'III b',
    'cōnspiciō -spexī -spectum -ere',
    'get sight of / заметить',
    ['', 'cōnspice_re', ''],
    ['', 'cōnspici_minī', ''],
  ],
  [
    1,
    'IV',
    'audīre',
    'hear; listen / слышать; слушать',
    ['audi_ō', 'audī_s', 'audi_t'],
    ['audī_mus', 'audī_tis', 'audiu_nt'],
  ],
  [
    2,
    'IV',
    'audīre',
    'hear; listen / слышать; слушать',
    ['audi_or', 'audī_ris', 'audī_tur'],
    ['audī_mur', 'audī_minī', 'audiu_ntur'],
  ],
  [
    3,
    'IV',
    'audīre',
    'hear; listen / слышать; слушать',
    ['audiēba_m', 'audiēbā_s', 'audiēba_t'],
    ['audiēbā_mus', 'audiēbā_tis', 'audiēba_nt'],
  ],
  [
    4,
    'IV',
    'audīre',
    'hear; listen / слышать; слушать',
    ['audiēba_r', 'audiēbā_ris', 'audiēbā_tur'],
    ['audiēbā_mur', 'audiēbā_minī', 'audiēba_ntur'],
  ],
  [
    5,
    'IV',
    'audīre',
    'hear; listen / слышать; слушать',
    ['audia_m', 'audiē_s', 'audie_t'],
    ['audiē_mus', 'audiē_tis', 'audie_nt'],
  ],
  [
    6,
    'IV',
    'audīre',
    'hear; listen / слышать; слушать',
    ['audia_r', 'audiē_ris', 'audiē_tur'],
    ['audiē_mur', 'audiē_minī', 'audie_ntur'],
  ],
  [
    13,
    'IV',
    'audīre',
    'hear; listen / слышать; слушать',
    ['', 'audī', ''],
    ['', 'audī_te', ''],
  ],
  [
    14,
    'IV',
    'audīre',
    'hear; listen / слышать; слушать',
    ['', 'audī_re', ''],
    ['', 'audī_minī', ''],
  ],
  [
    1,
    'IV',
    'fīnīre',
    'limit / ограничивать',
    ['fīni_ō', 'fīnī_s', 'fīni_t'],
    ['fīnī_mus', 'fīnī_tis', 'fīniu_nt'],
  ],
  [
    2,
    'IV',
    'fīnīre',
    'limit / ограничивать',
    ['fīni_or', 'fīnī_ris', 'fīnī_tur'],
    ['fīnī_mur', 'fīnī_minī', 'fīniu_ntur'],
  ],
  [
    3,
    'IV',
    'fīnīre',
    'limit / ограничивать',
    ['fīniēba_m', 'fīniēbā_s', 'fīniēba_t'],
    ['fīniēbā_mus', 'fīniēbā_tis', 'fīniēba_nt'],
  ],
  [
    4,
    'IV',
    'fīnīre',
    'limit / ограничивать',
    ['fīniēba_r', 'fīniēbā_ris', 'fīniēbā_tur'],
    ['fīniēbā_mur', 'fīniēbā_minī', 'fīniēba_ntur'],
  ],
  [
    5,
    'IV',
    'fīnīre',
    'limit / ограничивать',
    ['fīnia_m', 'fīniē_s', 'fīnie_t'],
    ['fīniē_mus', 'fīniē_tis', 'fīnie_nt'],
  ],
  [
    6,
    'IV',
    'fīnīre',
    'limit / ограничивать',
    ['fīnia_r', 'fīniē_ris', 'fīniē_tur'],
    ['fīniē_mur', 'fīniē_minī', 'fīnie_ntur'],
  ],
  [
    13,
    'IV',
    'fīnīre',
    'limit / ограничивать',
    ['', 'fīnī', ''],
    ['', 'fīnī_te', ''],
  ],
  [
    14,
    'IV',
    'fīnīre',
    'limit / ограничивать',
    ['', 'fīnī_re', ''],
    ['', 'fīnī_minī', ''],
  ],
  [
    1,
    'IV',
    'mollīre',
    'soften / размягчать',
    ['molli_ō', 'mollī_s', 'molli_t'],
    ['mollī_mus', 'mollī_tis', 'molliu_nt'],
  ],
  [
    2,
    'IV',
    'mollīre',
    'soften / размягчать',
    ['molli_or', 'mollī_ris', 'mollī_tur'],
    ['mollī_mur', 'mollī_minī', 'molliu_ntur'],
  ],
  [
    3,
    'IV',
    'mollīre',
    'soften / размягчать',
    ['molliēba_m', 'molliēbā_s', 'molliēba_t'],
    ['molliēbā_mus', 'molliēbā_tis', 'molliēba_nt'],
  ],
  [
    4,
    'IV',
    'mollīre',
    'soften / размягчать',
    ['molliēba_r', 'molliēbā_ris', 'molliēbā_tur'],
    ['molliēbā_mur', 'molliēbā_minī', 'molliēba_ntur'],
  ],
  [
    5,
    'IV',
    'mollīre',
    'soften / размягчать',
    ['mollia_m', 'molliē_s', 'mollie_t'],
    ['molliē_mus', 'molliē_tis', 'mollie_nt'],
  ],
  [
    6,
    'IV',
    'mollīre',
    'soften / размягчать',
    ['mollia_r', 'molliē_ris', 'molliē_tur'],
    ['molliē_mur', 'molliē_minī', 'mollie_ntur'],
  ],
  [
    13,
    'IV',
    'mollīre',
    'soften / размягчать',
    ['', 'mollī', ''],
    ['', 'mollī_te', ''],
  ],
  [
    14,
    'IV',
    'mollīre',
    'soften / размягчать',
    ['', 'mollī_re', ''],
    ['', 'mollī_minī', ''],
  ],
  [
    1,
    'IV',
    'polīre',
    'polish / полировать',
    ['poli_ō', 'polī_s', 'poli_t'],
    ['polī_mus', 'polī_tis', 'poliu_nt'],
  ],
  [
    2,
    'IV',
    'polīre',
    'polish / полировать',
    ['poli_or', 'polī_ris', 'polī_tur'],
    ['polī_mur', 'polī_minī', 'poliu_ntur'],
  ],
  [
    3,
    'IV',
    'polīre',
    'polish / полировать',
    ['poliēba_m', 'poliēbā_s', 'poliēba_t'],
    ['poliēbā_mus', 'poliēbā_tis', 'poliēba_nt'],
  ],
  [
    4,
    'IV',
    'polīre',
    'polish / полировать',
    ['poliēba_r', 'poliēbā_ris', 'poliēbā_tur'],
    ['poliēbā_mur', 'poliēbā_minī', 'poliēba_ntur'],
  ],
  [
    5,
    'IV',
    'polīre',
    'polish / полировать',
    ['polia_m', 'poliē_s', 'polie_t'],
    ['poliē_mus', 'poliē_tis', 'polie_nt'],
  ],
  [
    6,
    'IV',
    'polīre',
    'polish / полировать',
    ['polia_r', 'poliē_ris', 'poliē_tur'],
    ['poliē_mur', 'poliē_minī', 'polie_ntur'],
  ],
  [
    13,
    'IV',
    'polīre',
    'polish / полировать',
    ['', 'polī', ''],
    ['', 'polī_te', ''],
  ],
  [
    14,
    'IV',
    'polīre',
    'polish / полировать',
    ['', 'polī_re', ''],
    ['', 'polī_minī', ''],
  ],
  [
    1,
    'IV',
    'linīre',
    'smear / смазывать',
    ['lini_ō', 'linī_s', 'lini_t'],
    ['linī_mus', 'linī_tis', 'liniu_nt'],
  ],
  [
    2,
    'IV',
    'linīre',
    'smear / смазывать',
    ['lini_or', 'linī_ris', 'linī_tur'],
    ['linī_mur', 'linī_minī', 'liniu_ntur'],
  ],
  [
    3,
    'IV',
    'linīre',
    'smear / смазывать',
    ['liniēba_m', 'liniēbā_s', 'liniēba_t'],
    ['liniēbā_mus', 'liniēbā_tis', 'liniēba_nt'],
  ],
  [
    4,
    'IV',
    'linīre',
    'smear / смазывать',
    ['liniēba_r', 'liniēbā_ris', 'liniēbā_tur'],
    ['liniēbā_mur', 'liniēbā_minī', 'liniēba_ntur'],
  ],
  [
    5,
    'IV',
    'linīre',
    'smear / смазывать',
    ['linia_m', 'liniē_s', 'linie_t'],
    ['liniē_mus', 'liniē_tis', 'linie_nt'],
  ],
  [
    6,
    'IV',
    'linīre',
    'smear / смазывать',
    ['linia_r', 'liniē_ris', 'liniē_tur'],
    ['liniē_mur', 'liniē_minī', 'linie_ntur'],
  ],
  [
    13,
    'IV',
    'linīre',
    'smear / смазывать',
    ['', 'linī', ''],
    ['', 'linī_te', ''],
  ],
  [
    14,
    'IV',
    'linīre',
    'smear / смазывать',
    ['', 'linī_re', ''],
    ['', 'linī_minī', ''],
  ],
  [
    1,
    'IV',
    'pūnīre',
    'punish / наказывать',
    ['pūni_ō', 'pūnī_s', 'pūni_t'],
    ['pūnī_mus', 'pūnī_tis', 'pūniu_nt'],
  ],
  [
    2,
    'IV',
    'pūnīre',
    'punish / наказывать',
    ['pūni_or', 'pūnī_ris', 'pūnī_tur'],
    ['pūnī_mur', 'pūnī_minī', 'pūniu_ntur'],
  ],
  [
    3,
    'IV',
    'pūnīre',
    'punish / наказывать',
    ['pūniēba_m', 'pūniēbā_s', 'pūniēba_t'],
    ['pūniēbā_mus', 'pūniēbā_tis', 'pūniēba_nt'],
  ],
  [
    4,
    'IV',
    'pūnīre',
    'punish / наказывать',
    ['pūniēba_r', 'pūniēbā_ris', 'pūniēbā_tur'],
    ['pūniēbā_mur', 'pūniēbā_minī', 'pūniēba_ntur'],
  ],
  [
    5,
    'IV',
    'pūnīre',
    'punish / наказывать',
    ['pūnia_m', 'pūniē_s', 'pūnie_t'],
    ['pūniē_mus', 'pūniē_tis', 'pūnie_nt'],
  ],
  [
    6,
    'IV',
    'pūnīre',
    'punish / наказывать',
    ['pūnia_r', 'pūniē_ris', 'pūniē_tur'],
    ['pūniē_mur', 'pūniē_minī', 'pūnie_ntur'],
  ],
  [
    13,
    'IV',
    'pūnīre',
    'punish / наказывать',
    ['', 'pūnī', ''],
    ['', 'pūnī_te', ''],
  ],
  [
    14,
    'IV',
    'pūnīre',
    'punish / наказывать',
    ['', 'pūnī_re', ''],
    ['', 'pūnī_minī', ''],
  ],
  [
    1,
    'IV',
    'ferīre',
    'strike, smite / ударять, поражать',
    ['feri_ō', 'ferī_s', 'feri_t'],
    ['ferī_mus', 'ferī_tis', 'feriu_nt'],
  ],
  [
    2,
    'IV',
    'ferīre',
    'strike, smite / ударять, поражать',
    ['feri_or', 'ferī_ris', 'feri_tur'],
    ['ferī_mur', 'ferī_minī', 'feriu_ntur'],
  ],
  [
    3,
    'IV',
    'ferīre',
    'strike, smite / ударять, поражать',
    ['feriēba_m', 'feriēbā_s', 'feriēba_t'],
    ['feriēbā_mus', 'feriēbā_tis', 'feriēba_nt'],
  ],
  [
    4,
    'IV',
    'ferīre',
    'strike, smite / ударять, поражать',
    ['feriēba_r', 'feriēbā_ris', 'feriēbā_tur'],
    ['feriēbā_mur', 'feriēbā_minī', 'feriēba_ntur'],
  ],
  [
    5,
    'IV',
    'ferīre',
    'strike, smite / ударять, поражать',
    ['feria_m', 'feriē_s', 'ferie_t'],
    ['feriē_mus', 'feriē_tis', 'ferie_nt'],
  ],
  [
    6,
    'IV',
    'ferīre',
    'strike, smite / ударять, поражать',
    ['feria_r', 'feriē_ris', 'feriē_tur'],
    ['feriē_mur', 'feriē_minī', 'ferie_ntur'],
  ],
  [
    13,
    'IV',
    'ferīre',
    'strike, smite / ударять, поражать',
    ['', 'ferī', ''],
    ['', 'ferī_te', ''],
  ],
  [
    14,
    'IV',
    'ferīre',
    'strike, smite / ударять, поражать',
    ['', 'ferī_re', ''],
    ['', 'ferī_minī', ''],
  ],
  [
    1,
    'IV',
    'hauriō hausī haustum -īre',
    'draw; drink up / черпать; выпивать',
    ['hauri_ō', 'haurī_s', 'hauri_t'],
    ['haurī_mus', 'haurī_tis', 'hauriu_nt'],
  ],
  [
    2,
    'IV',
    'hauriō hausī haustum -īre',
    'draw; drink up / черпать; выпивать',
    ['hauri_or', 'haurī_ris', 'haurī_tur'],
    ['haurī_mur', 'haurī_minī', 'hauriu_ntur'],
  ],
  [
    3,
    'IV',
    'hauriō hausī haustum -īre',
    'draw; drink up / черпать; выпивать',
    ['hauriēba_m', 'hauriēbā_s', 'hauriēba_t'],
    ['hauriēbā_mus', 'hauriēbā_tis', 'hauriēba_nt'],
  ],
  [
    4,
    'IV',
    'hauriō hausī haustum -īre',
    'draw; drink up / черпать; выпивать',
    ['hauriēba_r', 'hauriēbā_ris', 'hauriēbā_tur'],
    ['hauriēbā_mur', 'hauriēbā_minī', 'hauriēba_ntur'],
  ],
  [
    5,
    'IV',
    'hauriō hausī haustum -īre',
    'draw; drink up / черпать; выпивать',
    ['hauria_m', 'hauriē_s', 'haurie_t'],
    ['hauriē_mus', 'hauriē_tis', 'haurie_nt'],
  ],
  [
    6,
    'IV',
    'hauriō hausī haustum -īre',
    'draw; drink up / черпать; выпивать',
    ['hauria_r', 'hauriē_ris', 'hauriē_tur'],
    ['hauriē_mur', 'hauriē_minī', 'haurie_ntur'],
  ],
  [
    13,
    'IV',
    'hauriō hausī haustum -īre',
    'draw; drink up / черпать; выпивать',
    ['', 'haurī', ''],
    ['', 'haurī_te', ''],
  ],
  [
    14,
    'IV',
    'hauriō hausī haustum -īre',
    'draw; drink up / черпать; выпивать',
    ['', 'haurī_re', ''],
    ['', 'haurī_minī', ''],
  ],
  [
    1,
    'IV',
    'sepeliō -īvī -pultum -īre',
    'bury, inter / хоронить, погребать',
    ['sepeli_ō', 'sepelī_s', 'sepeli_t'],
    ['sepelī_mus', 'sepelī_tis', 'sepeliu_nt'],
  ],
  [
    2,
    'IV',
    'sepeliō -īvī -pultum -īre',
    'bury, inter / хоронить, погребать',
    ['sepeli_or', 'sepelī_ris', 'sepelī_tur'],
    ['sepelī_mur', 'sepelī_minī', 'sepeliu_ntur'],
  ],
  [
    3,
    'IV',
    'sepeliō -īvī -pultum -īre',
    'bury, inter / хоронить, погребать',
    ['sepeliēba_m', 'sepeliēbā_s', 'sepeliēba_t'],
    ['sepeliēbā_mus', 'sepeliēbā_tis', 'sepeliēba_nt'],
  ],
  [
    4,
    'IV',
    'sepeliō -īvī -pultum -īre',
    'bury, inter / хоронить, погребать',
    ['sepeliēba_r', 'sepeliēbā_ris', 'sepeliēbā_tur'],
    ['sepeliēbā_mur', 'sepeliēbā_minī', 'sepeliēba_ntur'],
  ],
  [
    5,
    'IV',
    'sepeliō -īvī -pultum -īre',
    'bury, inter / хоронить, погребать',
    ['sepelia_m', 'sepeliē_s', 'sepelie_t'],
    ['sepeliē_mus', 'sepeliē_tis', 'sepelie_nt'],
  ],
  [
    6,
    'IV',
    'sepeliō -īvī -pultum -īre',
    'bury, inter / хоронить, погребать',
    ['sepelia_r', 'sepeliē_ris', 'sepeliē_tur'],
    ['sepeliē_mur', 'sepeliē_minī', 'sepelie_ntur'],
  ],
  [
    13,
    'IV',
    'sepeliō -īvī -pultum -īre',
    'bury, inter / хоронить, погребать',
    ['', 'sepelī', ''],
    ['', 'sepelī_te', ''],
  ],
  [
    14,
    'IV',
    'sepeliō -īvī -pultum -īre',
    'bury, inter / хоронить, погребать',
    ['', 'sepelī_re', ''],
    ['', 'sepelī_minī', ''],
  ],
  [
    1,
    'IV',
    'scīre',
    'know / знать',
    ['sci_ō', 'scī_s', 'sci_t'],
    ['scī_mus', 'scī_tis', 'sciu_nt'],
  ],
  [
    2,
    'IV',
    'scīre',
    'know / знать',
    ['sci_or', 'scī_ris', 'scī_tur'],
    ['scī_mur', 'scī_minī', 'sciu_ntur'],
  ],
  [
    3,
    'IV',
    'scīre',
    'know / знать',
    ['sciēba_m', 'sciēbā_s', 'sciēba_t'],
    ['sciēbā_mus', 'sciēbā_tis', 'sciēba_nt'],
  ],
  [
    4,
    'IV',
    'scīre',
    'know / знать',
    ['sciēba_r', 'sciēbā_ris', 'sciēbā_tur'],
    ['sciēbā_mur', 'sciēbā_minī', 'sciēba_ntur'],
  ],
  [
    5,
    'IV',
    'scīre',
    'know / знать',
    ['scia_m', 'sciē_s', 'scie_t'],
    ['sciē_mus', 'sciē_tis', 'scie_nt'],
  ],
  [
    6,
    'IV',
    'scīre',
    'know / знать',
    ['scia_r', 'sciē_ris', 'sciē_tur'],
    ['sciē_mur', 'sciē_minī', 'scie_ntur'],
  ],
  [
    13,
    'IV',
    'scīre',
    'know / знать',
    ['', 'scī', ''],
    ['', 'scī_te', ''],
  ],
  [
    14,
    'IV',
    'scīre',
    'know / знать',
    ['', 'scī_re', ''],
    ['', 'scī_minī', ''],
  ],
];
